name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Bump version"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: "v"
          minor-wording: "feat"
          major-wording: "feat!,BREAKING CHANGES"
          patch-wording: "fix"
          commit-message: "chore: bump version to {{version}} [skip ci]"

      - name: "Install dependencies"
        run: yarn --frozen-lockfile

      - name: "Publish NPM"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn publish --non-interactive --registry https://registry.npmjs.org/
